version: '3.8'

services:
  php:
    build: .
    container_name: php-container
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: hellofresh
      POSTGRES_USER: hellofresh
      POSTGRES_PASSWORD: hellofresh
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres-data:
